import = [
	# "~/.config/alacritty/poimandres.toml",
	# "~/.config/alacritty/nightfox.toml",
	"~/.config/alacritty/catppuccin-mocha.toml",
]

[env]
term = "xterm-256color"

[window]
decorations = "None"
startup_mode = "Maximized"
option_as_alt = "Both"
dynamic_padding = true

[font]
normal = { family = "GeistMono Nerd Font Mono", style = "Regular" }
size = 20
