[env]
term = "xterm-256color"

[window]
decorations = "None"
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
normal = { family = "GeistMono Nerd Font Mono", style = "Regular" }
size = 18

# # catppuccin mocha
# [colors.primary]
# background = "#1e1e2e"
# foreground = "#cdd6f4"
# dim_foreground = "#7f849c"
# bright_foreground = "#cdd6f4"
#
# [colors.cursor]
# text = "#1e1e2e"
# cursor = "#f5e0dc"
#
# [colors.vi_mode_cursor]
# text = "#1e1e2e"
# cursor = "#b4befe"
#
# [colors.search.matches]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.search.focused_match]
# foreground = "#1e1e2e"
# background = "#a6e3a1"
#
# [colors.footer_bar]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.hints.start]
# foreground = "#1e1e2e"
# background = "#f9e2af"
#
# [colors.hints.end]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.selection]
# text = "#1e1e2e"
# background = "#f5e0dc"
#
# [colors.normal]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"
#
# [colors.bright]
# black = "#585b70"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#a6adc8"
#
# [colors.dim]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"
#
# [[colors.indexed_colors]]
# index = 16
# color = "#fab387"
#
# [[colors.indexed_colors]]
# index = 17
# color = "#f5e0dc"

# # catppuccin latte
# [colors.primary]
# background = "#eff1f5"
# foreground = "#4c4f69"
# dim_foreground = "#8c8fa1"
# bright_foreground = "#4c4f69"
#
# [colors.cursor]
# text = "#eff1f5"
# cursor = "#dc8a78"
#
# [colors.vi_mode_cursor]
# text = "#eff1f5"
# cursor = "#7287fd"
#
# [colors.search.matches]
# foreground = "#eff1f5"
# background = "#6c6f85"
#
# [colors.search.focused_match]
# foreground = "#eff1f5"
# background = "#40a02b"
#
# [colors.footer_bar]
# foreground = "#eff1f5"
# background = "#6c6f85"
#
# [colors.hints.start]
# foreground = "#eff1f5"
# background = "#df8e1d"
#
# [colors.hints.end]
# foreground = "#eff1f5"
# background = "#6c6f85"
#
# [colors.selection]
# text = "#eff1f5"
# background = "#dc8a78"
#
# [colors.normal]
# black = "#bcc0cc"
# red = "#d20f39"
# green = "#40a02b"
# yellow = "#df8e1d"
# blue = "#1e66f5"
# magenta = "#ea76cb"
# cyan = "#179299"
# white = "#5c5f77"
#
# [colors.bright]
# black = "#acb0be"
# red = "#d20f39"
# green = "#40a02b"
# yellow = "#df8e1d"
# blue = "#1e66f5"
# magenta = "#ea76cb"
# cyan = "#179299"
# white = "#6c6f85"
#
# [colors.dim]
# black = "#bcc0cc"
# red = "#d20f39"
# green = "#40a02b"
# yellow = "#df8e1d"
# blue = "#1e66f5"
# magenta = "#ea76cb"
# cyan = "#179299"
# white = "#5c5f77"
#
# [[colors.indexed_colors]]
# index = 16
# color = "#fe640b"
#
# [[colors.indexed_colors]]
# index = 17
# color = "#dc8a78"

# # dayfox
# [colors.primary]
# background = "#f6f2ee"
# foreground = "#3d2b5a"
# dim_foreground = "#302b5d"
# bright_foreground = "#643f61"
#
# # [colors.cursor]
# # text = "#3d2b5a"
# # cursor = "#643f61"
#
# [colors.vi_mode_cursor]
# text = "#3d2b5a"
# cursor = "#287980"
#
# [colors.search.matches]
# foreground = "#3d2b5a"
# background = "#a4c1c2"
#
# [colors.search.focused_match]
# foreground = "#3d2b5a"
# background = "#396847"
#
# [colors.footer_bar]
# foreground = "#3d2b5a"
# background = "#d3c7bb"
#
# [colors.hints.start]
# foreground = "#3d2b5a"
# background = "#955f61"
#
# [colors.hints.end]
# foreground = "#3d2b5a"
# background = "#d3c7bb"
#
# [colors.selection]
# text = "#3d2b5a"
# background = "#e7d2be"
#
# [colors.normal]
# black = "#352c24"
# red = "#a5222f"
# green = "#396847"
# yellow = "#ac5402"
# blue = "#2848a9"
# magenta = "#6e33ce"
# cyan = "#287980"
# white = "#f2e9e1"
#
# [colors.bright]
# black = "#534c45"
# red = "#b3434e"
# green = "#577f63"
# yellow = "#b86e28"
# blue = "#4863b6"
# magenta = "#8452d5"
# cyan = "#488d93"
# white = "#f4ece6"
#
# [colors.dim]
# black = "#2d251f"
# red = "#8c1d28"
# green = "#30583c"
# yellow = "#924702"
# blue = "#223d90"
# magenta = "#5e2baf"
# cyan = "#22676d"
# white = "#cec6bf"
#
# [[colors.indexed_colors]]
# index = 16
# color = "#955f61"
#
# [[colors.indexed_colors]]
# index = 17
# color = "#a440b5"

# nightfox
[colors.primary]
background = "#192330"
foreground = "#cdcecf"
dim_foreground = "#aeafb0"
bright_foreground = "#d6d6d7"

[colors.cursor]
text = "#cdcecf"
cursor = "#aeafb0"

[colors.vi_mode_cursor]
text = "#cdcecf"
cursor = "#63cdcf"

[colors.search.matches]
foreground = "#cdcecf"
background = "#3c5372"

[colors.search.focused_match]
foreground = "#cdcecf"
background = "#81b29a"

[colors.footer_bar]
foreground = "#cdcecf"
background = "#29394f"

[colors.hints.start]
foreground = "#cdcecf"
background = "#f4a261"

[colors.hints.end]
foreground = "#cdcecf"
background = "#29394f"

[colors.selection]
text = "#cdcecf"
background = "#2b3b51"

[colors.normal]
black = "#393b44"
red = "#c94f6d"
green = "#81b29a"
yellow = "#dbc074"
blue = "#719cd6"
magenta = "#9d79d6"
cyan = "#63cdcf"
white = "#dfdfe0"

[colors.bright]
black = "#575860"
red = "#d16983"
green = "#8ebaa4"
yellow = "#e0c989"
blue = "#86abdc"
magenta = "#baa1e2"
cyan = "#7ad5d6"
white = "#e4e4e5"

[colors.dim]
black = "#30323a"
red = "#ab435d"
green = "#6e9783"
yellow = "#baa363"
blue = "#6085b6"
magenta = "#8567b6"
cyan = "#54aeb0"
white = "#bebebe"

[[colors.indexed_colors]]
index = 16
color = "#f4a261"

[[colors.indexed_colors]]
index = 17
color = "#d67ad2"
