lvim.colorscheme = "carbonfox"

reload "m.opts"
reload "m.keymaps"
reload "m.plugins"
reload "m.lsp"
reload "m.linters"
reload "m.formatters"
reload "m.code-actions"
reload "m.harpoon"
reload "m.builtins"
